# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.ci for more information
ci:
  autoupdate_schedule: weekly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.49.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        exclude: ^test\/.*$$
        args: [--no-eslintrc, --config, .eslintrc.js, --fix]
        additional_dependencies: [
            # https://www.npmjs.com/package/eslint
            "eslint@v8.49.0",
            # https://www.npmjs.com/package/eslint-plugin-editorconfig
            "eslint-plugin-editorconfig@4.0.3",
            # https://www.npmjs.com/package/@typescript-eslint/eslint-plugin
            "@typescript-eslint/eslint-plugin@6.7.0",
            # https://www.npmjs.com/package/@typescript-eslint/parser
            "@typescript-eslint/parser@6.7.0"
          ]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.2"
    hooks:
      - id: editorconfig-checker
        alias: ec
