# SPDX-FileCopyrightText: 2024 Gnuxie <Gnuxie@protonmail.com>
#
# SPDX-License-Identifier: 0BSD

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://pre-commit.ci for more information
ci:
  autoupdate_schedule: monthly
  skip: [npm-lint, npm-build]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext", "md"]
        exclude_types: [svg]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.6.1"
    hooks:
      - id: editorconfig-checker
        alias: ec
  - repo: https://github.com/fsfe/reuse-tool
    rev: v4.0.3
    hooks:
      - id: reuse
  - repo: local
    hooks:
      - id: npm-build
        name: npm build
        entry: npm run build:all
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: npm-lint
        name: linter
        entry: npm run lint
        language: system
        pass_filenames: false
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.0
    hooks:
      - id: check-renovate
        additional_dependencies: ["pyjson5"]
