version = 1
SPDX-PackageName = "Draupnir"
SPDX-PackageSupplier = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/the-draupnir-project/Draupnir"

[[annotations]]
path = "tsconfig.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "yarn.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "NOTICE"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "test/tsconfig.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "package.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "AFL-3.0"
