homeserver:
  # The Matrix server name, this will be the name of the server in your matrix id.
  domain: "localhost:9999"
  # The url for the appservice to call the client server API from.
  url: http://localhost:8081

# Database configuration for storing which Draupnirs have been provisioned.
db:
  engine: "postgres"
  connectionString: "postgres://mjolnir-tester:mjolnir-test@localhost:8083/mjolnir-test-db"

# A room you have created that scopes who can access the appservice.
# See docs/access_control.md
adminRoom: "#draupnir-admin:localhost:9999"

# Options for exposing web APIs.
web:
  # Whether to enable web APIs.
  enabled: true

  # The port to expose the webserver on. Defaults to 8080.
  port: 9001

  # The address to listen for requests on. Defaults to all addresses.
  # Be careful with this setting, as opening to the wide web will increase
  # your security perimeter.
  # We listen on all in harness because we might be getting requests through the docker gateway.
  address: "0.0.0.0"

  ui:
    enabled: true

# The directory the bot should store various bits of information in
dataPath: "/data/storage"

roomStateBackingStore:
  enabled: false
