// Copyright 2023 Gnuxie <Gnuxie@protonmail.com>
// Copyright 2018 New Vector Ltd
//
// SPDX-License-Identifier: Apache-2.0
//
// SPDX-FileAttributionText: <text>
// This modified file incorporates work from matrix-spec
// https://github.com/matrix-org/matrix-spec
// </text>
import { TSchema, Type } from "@sinclair/typebox";
import {
  StringEventIDSchema,
  StringRoomIDSchema,
  StringUserIDSchema,
} from "./StringlyTypedMatrix";
import { EDStatic } from "../Interface/Static";

export const EmptyContent = Type.Object({}, { additionalProperties: false });
export type EmptyContent = EDStatic<typeof EmptyContent>;

export type Event<Content extends TSchema = typeof EmptyContent> = EDStatic<
  ReturnType<typeof Event<Content>>
>;
export const Event = <Content extends TSchema>(Content: Content) =>
  Type.Object({
    content: Content,
    type: Type.String({
      description:
        "The type of event. This SHOULD be namespaced similar to Java package naming conventions e.g. 'com.example.subdomain.event.type'",
    }),
  });

export type UnsignedData = EDStatic<typeof UnsignedData>;
export const UnsignedData = Type.Object({
  age: Type.Optional(
    Type.Number({
      description:
        "The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.",
      format: "int64",
      example: 1567437,
    })
  ),
  redacted_because: Type.Optional(Type.Unknown()),
  transaction_id: Type.Optional(
    Type.String({
      description:
        "The client-supplied [transaction ID](/client-server-api/#transaction-identifiers), for example, provided via\n`PUT /_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId}`,\nif the client being given the event is the same one which sent it.\n",
    })
  ),
  prev_content: Type.Optional(Type.Unknown()),
});

export type SyncRoomEvent<Content extends TSchema = typeof EmptyContent> =
  EDStatic<ReturnType<typeof SyncRoomEvent<Content>>>;
export const SyncRoomEvent = <Content extends TSchema>(Content: Content) =>
  Type.Intersect([
    Event(Content),
    Type.Object({
      event_id: StringEventIDSchema,
      sender: StringUserIDSchema,
      origin_server_ts: Type.Number({
        description:
          "Timestamp in milliseconds on originating homeserver when this event was sent.",
        format: "int64",
      }),
      unsigned: Type.Optional(UnsignedData),
    }),
  ]);

export type RoomEvent<Content extends TSchema = typeof EmptyContent> = EDStatic<
  ReturnType<typeof RoomEvent<Content>>
>;
export const RoomEvent = <Content extends TSchema>(Content: Content) =>
  Type.Intersect([
    SyncRoomEvent(Content),
    Type.Object({
      room_id: StringRoomIDSchema,
    }),
  ]);

const StateKey = Type.Object({
  state_key: Type.String({
    description:
      "A unique key which defines the overwriting semantics for this piece of room state. This value is often a zero-length string. The presence of this key makes this event a State Event.\nState keys starting with an `@` are reserved for referencing user IDs, such as room members. With the exception of a few events, state events set with a given user's ID as the state key MUST only be set by that user.",
  }),
});

export type SyncStateEvent<Content extends TSchema = typeof EmptyContent> =
  EDStatic<ReturnType<typeof SyncStateEvent<Content>>>;
export const SyncStateEvent = <Content extends TSchema>(Content: Content) =>
  Type.Intersect([SyncRoomEvent(Content), StateKey]);

export type StateEvent<Content extends TSchema = typeof EmptyContent> =
  EDStatic<ReturnType<typeof StateEvent<Content>>>;
export const StateEvent = <Content extends TSchema>(Content: Content) =>
  Type.Intersect([RoomEvent(Content), StateKey]);

export type StrippedStateEvent = EDStatic<typeof StrippedStateEvent>;
export const StrippedStateEvent = Type.Object({
  content: Type.Unknown(),
  state_key: Type.String({ description: "The `state_key` for the event." }),
  type: Type.String({ description: "The `type` for the event." }),
  sender: StringUserIDSchema,
});
