version = 1

[[annotations]]
path = "*.gif"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "REUSE.toml"
precedence = "aggregate"
SPDX-FileCopyrightText = "Gnuxie <Gnuxie@protonmail.com>"
SPDX-License-Identifier = "CC0-1.0"
