/**
 * Copyright (C) 2022 Gnuxie <Gnuxie@protonmail.com>
 * All rights reserved.
 *
 * This file is modified and is NOT licensed under the Apache License.
 * This modified file incorperates work from mjolnir
 * https://github.com/matrix-org/mjolnir
 * which included the following license notice:

Copyright 2019, 2021 The Matrix.org Foundation C.I.C.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 *
 * However, this file is modified and the modifications in this file
 * are NOT distributed, contributed, committed, or licensed under the Apache License.
 */

import * as fs from "fs";
import { load } from "js-yaml";
import { MatrixClient, LogService } from "matrix-bot-sdk";
import Config from "config";
import path from "path";
import { ConfigSchema } from "./ConfigSchema";
import { ActionResult, DecodeException, Logger, StringRoomID, Value, isError } from "matrix-protection-suite";
import { ValueError } from "@sinclair/typebox/errors"

const log = new Logger('config');

/**
 * The configuration, as read from production.yaml
 *
 * See file default.yaml for the documentation on individual options.
 */
// The object is magically generated by external lib `config`
// from the file specified by `NODE_ENV`, e.g. production.yaml
// or harness.yaml.
export interface IConfig extends ConfigSchema {
    RUNTIME: {
        client?: MatrixClient;
    };
}

const defaultConfig: IConfig = {
    homeserverUrl: "http://localhost:8008",
    rawHomeserverUrl: "http://localhost:8008",
    accessToken: "NONE_PROVIDED",
    pantalaimon: {
        use: false,
        username: "",
        password: "",
    },
    dataPath: "/data/storage",
    managementRoom: '!noop:example.org' as StringRoomID,
    acceptInvitesFromSpace: '!noop:example.org' as StringRoomID,
    autojoinOnlyIfManager: true,
    recordIgnoredInvites: false,
    logLevel: "INFO",
    logMutedModules: ['MatrixHttpClient', 'MatrixClientLite'],
    noop: false,
    disableServerACL: false,
    automaticallyRedactForReasons: ["spam", "advertising"],
    protectAllJoinedRooms: false,
    backgroundDelayMS: 500,
    pollReports: false,
    displayReports: true,
    commands: {
        allowNoPrefix: false,
        additionalPrefixes: ["draupnir"],
        confirmWildcardBan: true,
        ban: {
            defaultReasons: [
                "spam",
                "brigading",
                "harassment",
                "disagreement",
            ]
        }
    },
    protections: {
        wordlist: {
            words: [],
            minutesBeforeTrusting: 20
        }
    },
    health: {
        healthz: {
            enabled: false,
            port: 8080,
            address: "0.0.0.0",
            endpoint: "/healthz",
            healthyStatus: 200,
            unhealthyStatus: 418,
        },
        sentry: undefined,
    },
    web: {
        enabled: false,
        port: 8080,
        address: "localhost",
        abuseReporting: {
            enabled: false,
        },
    },
    roomStateBackingStore: {
        enabled: false,
    },
    experimentalRustCrypto: false,

    // Needed to make the interface happy.
    RUNTIME: {
    },
};

export function getDefaultConfig(): IConfig {
    return Config.util.cloneDeep(defaultConfig);
}

/**
 * @returns The users's raw config, deep copied over the `defaultConfig`.
 */
function readConfigSource(): Record<string, unknown> {
    const explicitConfigPath = getCommandLineOption(process.argv, "--draupnir-config");
    if (explicitConfigPath !== undefined) {
        const content = fs.readFileSync(explicitConfigPath, "utf8");
        const parsed = load(content);
        return Config.util.extendDeep({}, defaultConfig, parsed);
    } else {
        return Config.util.extendDeep({}, defaultConfig, Config.util.toObject());
    }
}

function readConfigSourceAndValidate(): ActionResult<IConfig, DecodeException> {
    const source = readConfigSource();
    const decodedSource = Value.Decode(ConfigSchema, source, {suppressLogOnError: true});
    return decodedSource as ActionResult<IConfig, DecodeException>;
}

function renderValidationError(error: ValueError): void {
    log.error(
        `Config value at path ${error.path} failed to validate with value:`,
        error.value,
        `and the following message:`,
        error.message
    );
    log.info(`Here is the description for ${error.path}:`, error.schema.description);
}

export function read(): IConfig {
    const configResult = readConfigSourceAndValidate();
    if (isError(configResult)) {
        configResult.error.errors.forEach(renderValidationError)
        if (configResult.error.errors.length === 0) {
            log.error(`Config error:`, configResult.error.exception);
        }
        throw new TypeError(`Config file failed validation`);
    }
    const config = configResult.ok;
    const explicitAccessTokenPath = getCommandLineOption(process.argv, "--access-token-path");
    const explicitPantalaimonPasswordPath = getCommandLineOption(process.argv, "--pantalaimon-password-path");
    if (explicitAccessTokenPath !== undefined) {
        config.accessToken = fs.readFileSync(explicitAccessTokenPath, "utf8");
    }
    if (explicitPantalaimonPasswordPath) {
        config.pantalaimon.password = fs.readFileSync(explicitPantalaimonPasswordPath, "utf8");
    }
    return config;
}


/**
 * Provides a config for each newly provisioned mjolnir in appservice mode.
 * @param managementRoomId A room that has been created to serve as the mjolnir's management room for the owner.
 * @returns A config that can be directly used by the new mjolnir.
 */
export function getProvisionedMjolnirConfig(managementRoomId: string): IConfig {
    // These are keys that are allowed to be configured for provisioned mjolnirs.
    // We need a restricted set so that someone doesn't accidentally enable webservers etc
    // on every created Mjolnir, which would result in very confusing error messages.
    const allowedKeys = [
        "commands",
        "verboseLogging",
        "logLevel",
        "syncOnStartup",
        "verifyPermissionsOnStartup",
        "fasterMembershipChecks",
        "automaticallyRedactForReasons",
        "protectAllJoinedRooms",
        "backgroundDelayMS",
    ];
    const configTemplate = read(); // we use the standard bot config as a template for every provisioned mjolnir.
    const unusedKeys = Object.keys(configTemplate).filter(key => !allowedKeys.includes(key));
    if (unusedKeys.length > 0) {
        LogService.warn("config", "The config provided for provisioned mjolnirs contains keys which are not used by the appservice.", unusedKeys);
    }
    const config = Config.util.extendDeep(
        getDefaultConfig(),
        allowedKeys.reduce((existingConfig: any, key: string) => {
            return { ...existingConfig, [key]: configTemplate[key as keyof IConfig] }
        }, {})
    );

    config.managementRoom = managementRoomId;
    config.protectedRooms = [];
    return config;
}

export const PACKAGE_JSON = (() => {
    try {
        return JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf-8'));
    } catch (e) {
        LogService.error("config", "Could not read Draupnir package.json", e);
        return {};
    }
})();

export const SOFTWARE_VERSION = (() => {
    let versionFile;
    const defaultText = PACKAGE_JSON.version ?? "A version was either not provided when building Draupnir or could not be read.";
    try {
        versionFile = fs.readFileSync(path.join(__dirname, '../version.txt'), 'utf-8');
    } catch (e) {
        LogService.error("config", "Could not read Draupnir version", e);
        versionFile = defaultText;
    }
    // it's important to ignore the newline if the version is going to be put
    // into <pre> or <code> where it will create an unnecessary newline.
    return /^(.*)$/m.exec(versionFile)?.at(0) ?? defaultText;
})();

export const DOCUMENTATION_URL = "https://the-draupnir-project.github.io/draupnir-documentation/";

// Command line related functions

/**
 * Grabs an option from the command line and checks if it exists.
 * @param args Program options
 * @param optionName Option name
 * @returns True if the option is present, otherwise false.
 */
function isCommandLineOptionPresent(args: string[], optionName: string): boolean {
    return args.includes(optionName);
}

/**
 * Grabs an option's value from program options if it exists, otherwise returns undefined.
 * @param args Program options
 * @param optionName Option name
 * @returns The value passed to the option, or undefined if the option is not specified.
 * @throws Error if the option is present but has no value.
 */
function getCommandLineOption(args: string[], optionName: string): string | undefined {
    // We don't want to throw if the option is not present
    if(!isCommandLineOptionPresent(args, optionName)) {
        return undefined;
    }

    const optionIndex = args.indexOf(optionName);

    //check if the next index is not an option
    if (args[optionIndex + 1] && !args[optionIndex + 1].startsWith("--")){
        return args[optionIndex + 1];
    }

    // No value was provided, or the next argument is another option
    throw new Error(`No value provided for ${optionName}`);
}
