# SPDX-FileCopyrightText: 2026 Catalan Lover <catalanlover@protonmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Workflow Gate

on:
  workflow_run:
    workflows:
      - "GHCR - Development Branches"
      - "Docker Hub - Release"
      - "Docker Hub - Latest"
      - "Docker Hub - Develop"
      - "GHCR - Release"
      - "Tests"
      - "GHCR - Latest"
      - "Contribution requirements"
    types: [completed]

permissions:
  checks: write

jobs:
  gate:
    runs-on: ubuntu-latest
    if:
      github.event.workflow_run.event == 'pull_request' ||
      startsWith(github.event.workflow_run.head_branch, 'develop')
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Aggregate workflow status
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        with:
          script: |
            const gateScript = require('./.github/scripts/gate.js');
            await gateScript({ github, context });
